[project]
name = "fx-1-minute-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "deltalake[pyarrow]>=1.1.3",
    "ipykernel>=6.30.0",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
